apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-ntt
  namespace: ntt
spec:
  replicas: 1
  selector:
    matchingLabel:
      name: app
  template:
    spec:
      containers:
      - name: application-ntt
        image: rakeshnagarajan/ntt:v1
        imagePullPolicy: always
        
